version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - ${LOCAL_SERVER_PORT}:80
    depends_on:
      - db
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./src/${PLUGIN_NAME}:/var/www/html/wp-content/plugins/${PLUGIN_NAME}
    networks:
      - dev-network

  db:
    image: mariadb:10.4
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
